### ISSUE TITLE
Add Wheelchairs [Basic]

### ISSUE THREAD

**Issue by Cheeses-The-Mac** [echo-station/echo-station#31]
## Summary
Wheelchairs should be added to allow for players to roleplay as an individual with low mobility, thus expanding the potential for roleplay-oriented interactions. Wheelchairs would likely act similar to a mech in terms of movement, but further PRs may be generated to add bells and whistles.

I believe that wheelchairs would be a fun feature to have in SS14, and would be a good first/first few issues for a new developer to get used to working with the project.

## Subtasks

- [x] **Add Low Mobility Role**
Add a UI role named ‘Low Mobility’ with no functionality.

- [x] **Add Move Speed Penalty when Low Mobility Role is Selected**
When the ‘Low Mobility’ role is selected, the player has lower base move speed.
- [x] **Add Wheelchair Item**
Add a ‘wheelchair’ object with a temporary sprite and no functionality.

- [x] **Link Wheelchair to Low Mobility Role**
When the ‘Low Mobility’ role is selected, the player spawns with a wheelchair.

- [x] **"Borrow" Wheelchair Spritework**
"Borrow" wheelchair sprites for the four base move directions.

- [x] **Allow Player to Sit in Wheelchair**
The player should be able to sit in a wheelchair as if it was a chair.

- [x] **Allow Player to Move Wheelchair**
When the player is sitting in a wheelchair, they can move in it as if they were moving a player with base move speed.

**Comment by redmushie** [comment]
They were in the game originally. Context:
https://github.com/space-wizards/space-station-14/pull/24681

**Comment by Cheeses-The-Mac** [comment]
Please assign to me when convenient - I've actually made some decent progress with this, at least in terms of adding a trait and giving it functionality. I'd expect actually adding the wheelchair might be a bit harder, but we'll see.
